# Generated by Django 3.1 on 2020-09-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ManyToManyField(to='core.Status'),
        ),
    ]
