# Generated by Django 3.1 on 2020-09-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200930_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
