# Generated by Django 3.1 on 2020-10-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
